In [1]:
import numpy as np
import tensorflow as tf


In [2]:
V = np.array([1,2,3,4])
V


array([1, 2, 3, 4])

In [3]:
M= np.array([[1,2],[3,4],[5,6,],[7,8]])
M


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
T = tf.constant([[1,2]], dtype=tf.int32)
T

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

Multiplication of two matrix

In [5]:
A= np.array([[1,2],[3,4],[5,6,],[7,8]])
B= np.array([[2,2],[4,4],[6,6,],[7,8]])
C  = A*B
C

array([[ 2,  4],
       [12, 16],
       [30, 36],
       [49, 64]])

Vector Multiplication

In [6]:
V1= np.array([1,2,3,4])
V2=np.array([3,2,5,4])
Vector_multiplication = V1*V2
Vector_multiplication

array([ 3,  4, 15, 16])

Tensors Multiplication

In [7]:
T1 = tf.constant([[1,2],[3,4],[5,6,],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6,],[9,8]] )
tensor_multiplication= T1*T2
tensor_multiplication

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [15, 16],
       [35, 36],
       [63, 64]], dtype=int32)>

Addition of two vectors

In [8]:
V1= np.array([1,2,3,4])
V2=np.array([3,2,5,4])
Vector_Addition = V1+V2
Vector_Addition

array([4, 4, 8, 8])

Addition of two matrix

In [9]:
M1= np.array([[1,2],[3,4],[5,6,],[7,8]])
M2= np.array([[2,2],[4,4],[6,6,],[7,8]])
matrix_Addition= M1+M2
matrix_Addition

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [14, 16]])

Tensor Addition

In [10]:
T1 = tf.constant([[1,2],[3,4],[5,6,],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6,],[9,8]] )
tensor_Addition= T1+T2
tensor_Addition

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  4],
       [ 8,  8],
       [12, 12],
       [16, 16]], dtype=int32)>

Addition of matrix and vector

In [11]:
M_1= np.array([[2],[4],[6,],[8]])
V1= np.array([1,2,3,4])
V1_M_1= M_1+V1
V1_M_1

array([[ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [ 9, 10, 11, 12]])

Matrix Dot product

In [12]:
D1=[2,-3]
D2=[4,3]
dotproduct=np.dot(D1,D2)
dotproduct

-1

Matrix of Inverse

In [ ]:
Matrix=np.array([[1,2,3],[3,4,5],[8,4,9]])
Inverse_Matrix=np.linalg.inv(Matrix)
Inverse_Matrix

array([[-0.88888889,  0.33333333,  0.11111111],
       [-0.72222222,  0.83333333, -0.22222222],
       [ 1.11111111, -0.66666667,  0.11111111]])